### ISSUE TITLE
błąd z odpalaniem animacji

### ISSUE THREAD

**Issue by zenoxx11** [Maathias/iledopapiezowej#3]
kiedy zmieni sie godzine w systemie na 21:37 poczeka do 21:38 i zmieni czas na inny to odpala sie animacja z papieżowej

**Comment by Maathias** [comment]
Nie jestem w stanie odtworzyć problemu.
Poza tym, to raczej nie jest coś co można naprawić od strony JS. Counter po prostu bierze czas systemowy, nie widze innego wyjścia
